---
title: "Compare significant metabolites with the PLS results"
author: "David Garrido Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r message=FALSE, warning=FALSE}
packages <- c("tidyverse", "devtools", "tools", "kableExtra", "UpSetR")

for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    if (package == "NormalizeMets") {
      devtools::install_github("metabolomicstats/NormalizeMets")
    } else {
      install.packages(package)
    }
  }
  library(package, character.only = TRUE)
}


cbind.fill <- function(...){
  nm <- list(...) 
  nm<-lapply(nm, as.matrix)
  n <- max(sapply(nm, nrow)) 
  do.call(cbind, lapply(nm, function (x) {
    rbind(x, matrix(NA, n-nrow(x), ncol(x)))
  }))
}
```



```{r warning=FALSE}
imputed_input_folder <- "../1_Data/Untargeted_metabolomic_data/Imputed_ready_to_use"
common_input_folder <- "../1_Data/Untargeted_metabolomic_data/Common_ready_to_use"
output_folder <- "../Supplementary_tables"

#stats_values <- list()
#LFC_limit <- "LFC_limit"; stats_values[[LFC_limit]] <- 2
#alpha_value <- "alpha_value"; stats_values[[alpha_value]] <- 0.01

imputed_files <- list.files(imputed_input_folder)
imputed_files1 <- imputed_files[grepl("significant", imputed_files, ignore.case = T)]
imputed_files2 <- imputed_files[grepl("PLS", imputed_files, ignore.case = T)]


common_files <- list.files(common_input_folder)
common_files1 <- common_files[grepl("significant", common_files, ignore.case = T)]
common_files2 <- common_files[grepl("PLS", common_files, ignore.case = T)]
```



```{r}

my_colors <- c("magenta2", "aquamarine3", "red2", "orange", "purple")
comparatives <- c("A", "B", "C", "D", "E")
j = 0

for (i in imputed_files1){
  # Import .csv files with the significant metabolites 
  ## Significant Imputed NA metabolites
  data_path <- file.path(imputed_input_folder, i)
  data1 <- read.csv(data_path) 
  data1 <- c(data1[, 1], data1[, 2]) %>% na.omit()
  ## Significant Only common metabolites
  data_path <- file.path(common_input_folder, i)
  data2 <- read.csv(data_path)
  data2 <- c(data2[, 1], data2[, 2]) %>% na.omit()
  ## PLS Imputed NA metabolites
  data_path <- file.path(imputed_input_folder, paste0(sub("_.*.?", "", i), "_PLS_loadings.csv"))
  data3 <- read.csv(data_path)
  data3 <- data3$. 
  ## PLS Only common metabolites
  data_path <- file.path(common_input_folder, paste0(sub("_.*.?", "", i), "_PLS_loadings.csv"))
  data4 <- read.csv(data_path)
  data4 <- data4$.
    
  significant <- list("Imputed Significant" = data1, "Common Significant" = data2,
                      "Imputed PLS" = data3, "Common PLS" = data4)
  
  
  j = j+1
  
  # Upset diagram
  plot <- upset(fromList(significant),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of significant \n metabolites",
      mainbar.y.label = NULL, 
      set_size.show	= T, matrix.color = my_colors[j],
      set_size.scale_max = max(sapply(significant, length))+50,
      text.scale = c(1.5, 1.5, 1, 1, 1.4, 2), order.by = "freq") 
  print(plot)
    
}
```


