---
title: "Tables with metabolites and tehir ID"
author: "David Garrido Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
packages <- c("tidyverse", "devtools", "tools")

for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    if (package == "NormalizeMets") {
      devtools::install_github("metabolomicstats/NormalizeMets")
    } else {
      install.packages(package)
    }
  }
  library(package, character.only = TRUE)
}

cbind.fill <- function(...){
  nm <- list(...) 
  nm<-lapply(nm, as.matrix)
  n <- max(sapply(nm, nrow)) 
  do.call(cbind, lapply(nm, function (x) {
    rbind(x, matrix(NA, n-nrow(x), ncol(x)))
  }))
}
```


```{r}
# Import csv files downloaded previously. 
## Imputed metabolites must include the global comparative
input_folder <-  "../1_Data/Comparative_G/Untargeted_metabolomic_data/Ready_to_use"
files <- list.files(input_folder)
files <- files[grepl("mets_names", files, ignore.case = T)]
input_folder1 <-  "../1_Data/Untargeted_metabolomic_data/Imputed_ready_to_use"
files1 <- list.files(input_folder1)
files1 <- files1[grepl("mets_names", files1, ignore.case = T)]

## Common metabolites must include the global comparative
input_folder2 <-  "../1_Data/Untargeted_metabolomic_data/Common_ready_to_use"
files2 <- list.files(input_folder2)
files2 <- files2[grepl("mets_names", files2, ignore.case = T)]

output_folder <- "../Supplementary_tables"
```


```{r}

# Upload pls data and set column names according with their origin
for (i in files){
  data_path <- file.path(input_folder, i)
  data <- read.csv(data_path)
  name <- paste0("Imputed", "_", sub("_.*.?", "", i), "_save")
  assign(name, data)
}

for (i in files1){
  data_path <- file.path(input_folder1, i)
  data <- read.csv(data_path)
  name <- paste0("Imputed", "_", sub("_.*.?", "", i), "_save")
  assign(name, data)
}

for (i in files2){
  data_path <- file.path(input_folder2, i)
  data <- read.csv(data_path)
  name <- paste0("Common", "_", sub("_.*.?", "", i), "_save")
  assign(name, data)
}
```


```{r}
env <- ls()
env_delete <- env[!grepl("save|cbind.fill|output_folder",
                         env, perl = TRUE)]
rm(list = env_delete, "env", "env_delete")

files <- ls()
files <- files[grepl("save", files, perl = TRUE)]
```


```{r}
# Save Imputed metabolites in a same dataframe, with global comparative at the end
Imputed <- files[!grepl("Common", files, perl = T)]
index <- order(grepl("G", Imputed))
Imputed <- Imputed[index]

comparatives <- c("A", "B", "C", "D", "E", "G")

j = 1
data <- get(Imputed[1])
data <- rbind(colnames(data), data) 
data <- data %>% `colnames<-` (rep(paste("Comparative", comparatives[j]), 2))
j = j+1
for (i in Imputed[-1]) {
  data_i <- get(i)
  data_i <- rbind(colnames(data_i), data_i) 
  data_i <- data_i %>% `colnames<-` (rep(paste("Comparative", comparatives[j]), 2))
  j = j + 1
  data <- cbind.fill(data, data_i)
}
write.csv(data, file = paste0(output_folder, "/Supplementary_table_8_Imputed_Metabolites_ID.csv"),
          row.names = F, na = "", is.numeric(""))
Imputed <- data


# Save Common metabolites in a same dataframe
Common <- files[grepl("Common", files, perl = T)]

j = 1
data <- get(Common[1])
data <- rbind(colnames(data), data) 
data <- data %>% `colnames<-` (rep(paste("Comparative", comparatives[j]), 2))
j = j+1
for (i in Common[-1]) {
  data_i <- get(i)
  data_i <- rbind(colnames(data_i), data_i) 
  data_i <- data_i %>% `colnames<-` (rep(paste("Comparative", comparatives[j]), 2))
  j = j + 1
  data <- cbind.fill(data, data_i)
}
write.csv(data, file = paste0(output_folder, "/Supplementary_table_9_Common_Metabolites_ID.csv"),
          row.names = F, na = "", is.numeric(""))
Common <- data
```

