---
title: "PLS sensitivity test"
author: "David Garrido Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
packages <- c("tidyverse", "devtools", "tools")

for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    if (package == "NormalizeMets") {
      devtools::install_github("metabolomicstats/NormalizeMets")
    } else {
      install.packages(package)
    }
  }
  library(package, character.only = TRUE)
}

cbind.fill <- function(...){
  nm <- list(...) 
  nm<-lapply(nm, as.matrix)
  n <- max(sapply(nm, nrow)) 
  do.call(cbind, lapply(nm, function (x) {
    rbind(x, matrix(NA, n-nrow(x), ncol(x)))
  }))
}
```


```{r}

input_folder <-  "../1_Data/RDS_files"

files <- list.files(input_folder)
files <- files[grepl("predictions", files, ignore.case = T)]

comparatives <- c("A", "B", "C", "D", "E")

# Upload pls data and set column names according with their origin
for (i in files){
  data_path <- file.path(input_folder, i)
  data <- readRDS(data_path)
  if (grepl("Global", i)) {
    for (j in 1:length(data)){
      m = data[j]
      name <- paste0(sub("_.*.?", "", i), "_", names(data[j]), "_save")
      data2 <- m[[1]][[1]] %>% .[,-2] %>% as.data.frame() %>% 
        `colnames<-`(paste("PLS sensitivity test results of Comparative G"))
      assign(name, data2)
    }
  } else {
    for (j in 1:length(data)){
      m = data[j]
      name <- paste0(sub("_.*.?", "", i), "_", names(data[j]), "_save")
      data2 <- m[[1]][[1]] %>% .[,-2] %>% as.data.frame() %>% 
        `colnames<-`(paste("PLS sensitivity test results of Comparative", comparatives[j]))
      assign(name, data2)
    }
  }
}
```


```{r}
env <- ls()
env_delete <- env[!grepl("save|cbind.fill|input_folder",
                         env, perl = TRUE)]
rm(list = env_delete, "env", "env_delete")

files <- ls()
files <- files[grepl("save", files, perl = TRUE)]
```


```{r}
for (i in files){
  data <- get(i)
  data <- rbind(colnames(data), data)
  # Set as column name the analytical approach performed with original data
  if (!grepl("Common", i)) {
    data <- data %>% `colnames<-` ("Non-common Metabolites Imputation")
  } else {
    data <- data %>% `colnames<-` ("Only Common Metabolites")
  }
  assign(i, data)
}

# Save Imputed metabolites in a same dataframe, with global comparative at the end
Imputed <- files[!grepl("Common", files, perl = T)]
index <- order(grepl("Global", Imputed))
Imputed <- Imputed[index]

data <- get(Imputed[1])
for (i in Imputed[-1]) {
  data_i <- get(i)
  data <- rbind(data, data_i)
}
PLS_imputed <- data

# Save Common metabolites in a same dataframe
Common <- files[grepl("Common", files, perl = T)]

data <- get(Common[1])
for (i in Common[-1]) {
  data_i <- get(i)
  data <- rbind(data, data_i)
}
PLS_common <- data
```

```{r}
env <- ls()
env_delete <- env[!grepl("PLS|cbind.fill|input_folder",
                         env, perl = TRUE)]
rm(list = env_delete, "env", "env_delete")

files <- ls()
files <- files[grepl("PLS", files, perl = TRUE)]
```

```{r}
for (i in files){
  data <- get(i)
  data <- rownames_to_column(data, var = "Tested samples")
  assign(i, data)
}

data <- cbind.fill(PLS_imputed, PLS_common) %>% replace(., is.numeric(.), "NA")

write.csv(data, file = "../Supplementary_tables/Supplementary_table_7_PLS_Sensibility_essay.csv",
          row.names = F, na = "")
```

