---
title: "Compare significant metabolites"
author: "David Garrido Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r message=FALSE, warning=FALSE}
packages <- c("tidyverse", "devtools", "tools", "kableExtra", "UpSetR")

for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    if (package == "NormalizeMets") {
      devtools::install_github("metabolomicstats/NormalizeMets")
    } else {
      install.packages(package)
    }
  }
  library(package, character.only = TRUE)
}

```



```{r warning=FALSE}
input_folder <- "../../1_Data/Comparative_G/Untargeted_metabolomic_data/Ready_to_use"

R_file <- list.files(input_folder)
R_file <- R_file[grepl("significant", R_file, ignore.case = T)]

metaboanalyst_input <- "../../1_Data/MetaboAnalyst_data/"
metaboanalyst_file <- list.files(metaboanalyst_input)
metaboanalyst_file <- metaboanalyst_file[grepl("compG_volcano", metaboanalyst_file, ignore.case = T)]

## To Upset plot with the PLS results
#R_file1 <- R_file[grepl("significant", R_file, ignore.case = T)]
#R_file2 <- R_file[grepl("pls", R_file, ignore.case = T)]
```



```{r}
# Import .csv files with the significant metabolites 
## Global metabolites analyzed on RStudio
data_path <- file.path(input_folder, R_file)
data1 <- read.csv(data_path) 
data1 <- c(data1[, 1], data1[, 2]) %>% na.omit()
## Global metabolites analyzed on MetaboAnalyst
data_path <- file.path(metaboanalyst_input, metaboanalyst_file)
data2 <- read.csv(data_path)
data2 <- data2$X

  
significant <- list("Global on RStudio" = data1, "Global on MetaboAnalyst" = data2)


# Upset diagram
plot <- upset(fromList(significant),
    number.angles = 0, point.size = 3, line.size = 1,
    sets.x.label = "Number of significant \n metabolites",
    mainbar.y.label = NULL, 
    set_size.show	= T, matrix.color = "black",
    set_size.scale_max = max(sapply(significant, length))+50,
    text.scale = c(1.5, 1.5, 1, 1, 1.4, 2), order.by = "freq") 
print(plot)


data1 <- as.data.frame(data1) %>% `rownames<-`(.[, 1])
data2 <- as.data.frame(data2) %>% `rownames<-`(.[, 1])
  
significant <- merge(data1, data2, by = 0, all = T) %>% column_to_rownames(., "Row.names")

significant <- significant %>% arrange(., desc(complete.cases(.))) %>%
    `colnames<-` (c("Global Significant Metabolites by RStudio",
                    "Global Significant Metabolites by MetaboAnalyst"))
  
  write.csv(significant,
            file = "../../Supplementary_tables/Supplementary_table_6_Significant_metabolites_of_Comparative_G.csv",
            row.names = FALSE, na = "")


```


