---
title: "Targeted_metabolomic_data"
author: "David Garrido Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

# Functions and packages

```{r}
library(tidyverse)
library(plotly)
library(ggpubr)
library(htmltools)

generate_plot <- function(data, plot_title) {
  ggplot(data) +
    geom_bar(aes(x = Sampling_Day, y = OTA_ppb_mean), stat = "identity", fill = "forestgreen", alpha = 0.5) +
    geom_errorbar(aes(x = Sampling_Day, ymin = OTA_ppb_mean - OTA_ppb_sd, ymax = OTA_ppb_mean + OTA_ppb_sd),
                  width = 0.4, colour = "orange", alpha = 0.9, size = 1.5) +
    ggtitle(plot_title) + labs(x='Days of sampling since the onset of observed growth', y='Mean of OTA concentration [ppb]') +
    scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12))
}
```


# Import raw data:

## Calibration curve:

```{r}
# Import data
calibration_curve <- readxl::read_xlsx("../1_Data/OTA_patron_curve.xlsx")
colnames(calibration_curve) <- c("OTA_ppb", "AUC")

model <- lm(calibration_curve$AUC ~ calibration_curve$OTA_ppb)
m_summary <- summary(model)

p <- ggplot(data = calibration_curve, aes(x = OTA_ppb, y = AUC)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_text(x = 30, y = 33000000, label = paste("y =", coef(model)[2], "x", coef(model)[1]), size = 4, color = "black") +
  geom_text(x = 18, y = 30000000, label = paste("R^2 =", m_summary$r.squared), size = 4, color = "black") +
  labs(x = "OTA concentration [ppb]", y = "Area Under the Curve (AUC)", title = "     OTA Calibration curve") +
  theme_bw()

p

ggsave(filename = paste0("../Images/Directed_plots/Calibration_curve.png"), plot = p, width = 8, height = 6, dpi = 300)
```

## Import targeted metabolomic data

```{r}
# List with the sheet names and another with the save dataset name:
sheets <- c("Pn856 J17", "Pn856 J25", "Pn856 S17", "Pn856 S25",
            "Pn15 J17", "Pn15 J25", "Pn15 S17", "Pn15 S25",
            "Pn92 J17", "Pn92 J25", "Pn92 S17", "Pn92 S25")

saves <- c("J_856_17", "J_856_25", "S_856_17", "S_856_25",
           "J_15_17", "J_15_25", "S_15_17", "S_15_25",
           "J_92_17", "J_92_25", "S_92_17", "S_92_25")
```

```{r}
for (i in 1:length(sheets)){
  tmp_data <- readxl::read_xlsx(path = "../1_Data/Targeted_metabolomic_data.xlsx", sheet = sheets[[i]])
  tmp_data <- as.data.frame(tmp_data) # Save as data frame instead as a tibble
  colnames(tmp_data) <- c("Vial_codification", "Code_name", "AUC_OTA") # Change column name
  row.names(tmp_data) <- tmp_data$Vial_codification # Set first column as row names
  tmp_data <- tmp_data[,c(2,3)] # Eliminate first column
  tmp_data$AUC_OTA[tmp_data$AUC_OTA < 6e3] <- 0 # Apply a condition to set values less than 6*10^3 to 0
  tmp_data$AUC_OTA[tmp_data$AUC_OTA > 3e7] <- NA # Apply a condition to set values greater than 1^8 to NA
  assign(saves[[i]], tmp_data)
}
remove(tmp_data); remove(i)
```


# Data treatment:

## Generate the new data object with the sample information per day

```{r}
for (i in 1:length(saves)){
  df_name <- saves[[i]] # Obtain the name of the object that is going to be use
  tmp_df <- get(df_name) # Obtain the values of the object named as df_name
  
  # With this loop we obtain the OTA's ppb values from OTA's AUC values with the calibration curve equation.   We must multiplicate by 5 due to the dilution factor.
  for (j in 1:nrow(tmp_df)){
    tmp_df$ppb[j] <- ((tmp_df$AUC[j]-coef(model)[1])/coef(model)[2]*5)
    # Apply a condition to set values that have an AUC value = 0 as 0. We do this to prevent the value 0 of AUC from taking positive values when converted to ppb, which could lead to errors. In this case, since the calibration curve has a negative intercept term, converting an AUC of 0 to ppb would result in 2.840586837.
    tmp_df$ppb[tmp_df$ppb == ((0-coef(model)[1])/coef(model)[2]*5)] <- 0
    assign(saves[[i]], tmp_df)
  }
  
  # With the next loop we calculate the mean and SD, from ppb information, of each day for each dataset
  days <- data.frame(OTA_ppb_mean = numeric(), OTA_ppb_sd = numeric())
  for (m in seq(1, nrow(tmp_df), by = 3)) {
    if (m + 2 <= nrow(tmp_df)) {
      mean_day <- mean(tmp_df$ppb[m:(m + 2)], na.rm = TRUE)
      sd_day <- sd(tmp_df$ppb[m:(m + 2)], na.rm = TRUE)
      days <- rbind(days, data.frame(OTA_ppb_mean = mean_day, OTA_ppb_sd = sd_day))
    }
  }

  days <- cbind(Sampling_Day = c(1:12), days)
  assign(paste0("days_", saves[[i]]), days)
}
remove(days); remove(i); remove(j); remove(m); remove(mean_day);
remove(sd_day); remove(tmp_df); remove(df_name)
```

## Histogram plot

```{r message=FALSE, warning=FALSE}
# List with the sheet names and another with the save dataset name:
sheets <- c("Pn856 agar-ham 0.94 aw (J17)", "Pn856 agar-ham 0.90 aw (J25)", "Pn856 dfs-agar 0.94 aw (S17)", "Pn856 dfs-agar 0.90 aw (S25)",
            "Pn15 agar-ham 0.94 aw (J17)", "Pn15 agar-ham 0.90 aw (J25)", "Pn15 dfs-agar 0.94 aw (S17)", "Pn15 dfs-agar 0.90 aw (S25)",
            "Pn92 agar-ham 0.94 aw (J17)", "Pn92 agar-ham 0.90 aw (J25)", "Pn92 dfs-agar 0.94 aw (S17)", "Pn92 dfs-agar 0.90 aw (S25)")

plots <- list()
for (i in 1:length(saves)) {
  tmp_df <- get(paste0("days_", saves[[i]]))
  plot_title <- paste("Amount of OTA produced per day by", (as.character(sheets[[i]])))
  p <- generate_plot(tmp_df, plot_title) + 
    theme(plot.title = element_text(hjust = 0.5, color="black", size=14, face="bold"))
  ggsave(filename = paste0("../Images/Directed_plots/Plot_OTA_targeted_",
                           saves[[i]], ".png"), plot = p, width = 8, height = 6, dpi = 300)
  p <- ggplotly(p, tooltip ="all") 
  plots[[i]] <- p
}
```


```{r echo=FALSE}
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]
plots[[6]]
plots[[7]]
plots[[8]]
plots[[9]]
plots[[10]]
plots[[11]]
plots[[12]]
```

